name: stats
dependencies:
  - python
  - numpy
  - pandas
  - seaborn
  - matlplotlib
  - plotly
  - time
  - streamlit
  - datetime
  - sys
  - requests
  - sys
  - time
  - matplotlib
  - datetime
