name: stats
dependencies:
  - python
  - numpy
  - pandas
  - seaborn
  - matlplotlib
  - plotly
  - time
  - streamlit
  - datetime
  - sys
  - requests
  - streamlit
  - folium
  - geopy
  - IPython
  - streamlit_folium
