name: stats
dependencies:
  - python
  - numpy=1.18.4
  - pandas=1.0.3
  - seaborn=0.10.1
  - matlplotlib=3.2.1
  - plotly=5.3.0
  - time
  - streamlit=0.87.0
  - datetime
  - sys
  - requests=2.23.0
  - streamlit_folium=0.4.0
